### PR TITLE
include arm builds

### PR DESCRIPTION
**Pull request by gutmensch**

### CODE REVIEW

**Comment by bundyland** [comment]
@gutmensch 
Any chance to have these PRs fixed and merged? Would be nice to enjoy the dmarc reporter on my Hetzner ARM host.

Thanks a lot.

**Comment by thebootable** [comment]
as the logs on the PR-fails are no longer available, could you retry to see what the problem was? ARM should be a good addition to this tool, looking at Raspberry Pi and the mentioned Hetzner ARM instances.

**Comment by gutmensch** [comment]
@thebootable unfortunately the php source image is not available yet as arm build :-/ I had planned to switch to a complete own image (that I use elsewhere already) to enable arm builds, but haven't come around yet to work on it

**Comment by StoneMonarch** [comment]
Unless for cleanliness, I dont think any changes need to be made to anything other than the actions workflow to support ARM. Builds fine using buildx locally on the current trafex/php-nginx image, just need to modify the actions workflow which I have done [here](https://github.com/StoneMonarch/docker-dmarc-report-arm/blob/master/.github/workflows/docker-image.yml) however I am not maintaning it and do not think its PR ready.

**Pull request merged**
